version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: reservation-purchase-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: reservation-purchase
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD : password

  redis:
    image: redis:latest
    container_name: reservation-purchase-redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:latest
    container_name: reservation-purchase-rabbitmq
    ports:
      - "5672:5672" # rabbit amqp port
      - "15672:15672" # manage port
    environment:
      - RABBITMQ_DEFAULT_USER=admin       # 기본사용자 이름
      - RABBITMQ_DEFAULT_PASS=admin123!@# # 기본사용자 비밀번호